### ISSUE TITLE
Wüstenwind

### ISSUE THREAD

**Issue by Tobias-Trautmann** [Tobias-Trautmann/Liederschuh_Issues#10]
Wir haben zwar Akkorde für die erste Strophe, allerdings nicht für die folgenden drei. Bitte klärt uns über die restlichen Akkorde auf.
![image](https://user-images.githubusercontent.com/59808547/123184071-34707b80-d493-11eb-8472-98c6fe9d7838.png)

**Comment by peribaeri** [comment]
Strophen sind die gleichen Akkorde wie beim Part "Ballen die Wetter ... hitzig und schwer."
