### ISSUE TITLE
Und ganz doll mich

### ISSUE THREAD

**Issue by Tobias-Trautmann** [Tobias-Trautmann/Liederschuh_Issues#3]
Und ganz doll mich beinhaltet Shakin Stevens. Den kennt aber nun keiner mehr und darum brauchen wir einen Ersatz für ihn
![image](https://user-images.githubusercontent.com/59808547/123183066-02f6b080-d491-11eb-9c0b-c3b22fa4c5ec.png)

**Comment by peribaeri** [comment]
Mir würde einfallen:
Justin Bieber, Michael Jackson, Elvis Preasley, Stevie Wonder, David Bowie, Peter Maffay, ...
Ich würde zu Michael Jackson tendieren, da macht man sich am wenigsten Feinde bzgl Musikgeschmack und so
ansonsten hilft google: "bekannte Sänger" und man findet listen über listen ...

**Comment by Tobias-Trautmann** [comment]
DIE VAGANTEN KOMMEN
