### ISSUE TITLE
Holland

### ISSUE THREAD

**Issue by Tobias-Trautmann** [Tobias-Trautmann/Liederschuh_Issues#31]
Bitte Aufklärung über Akkorde, wahrscheinlich zu lesen als: eigentlich D4 aber D geht auch. Finde ich sehr unschön, hätte gerne nur ein Version.
![image](https://user-images.githubusercontent.com/59808547/124178459-df93bd00-dab1-11eb-8e82-6f4ced2de942.png)

**Comment by peribaeri** [comment]
kenne das lied nicht, aber würde allgemein einfach "D4" hinschreiben. jeder der das nicht hinkriegt wird einfach ein normales D spielen. ggf. wäre das auch etwas für den Gitarrenteil: "Wenn ihr die Variationen von Akkorden nicht könnt, könnt ihr einfach den Grundakkord spielen, also statt E7 E und statt D4 D" oder sowas in die Richtung
