### ISSUE TITLE
Titanic

### ISSUE THREAD

**Issue by Tobias-Trautmann** [Tobias-Trautmann/Liederschuh_Issues#38]
![image](https://user-images.githubusercontent.com/59808547/127495479-b45413fe-1df0-46ca-a41f-a5b75334a439.png)
bitte setzt die akkorde über dem 1912 richtig

**Comment by peribaeri** [comment]
e auf die erste Silbe von hundred und a auf die erste Silbe von twelve 

Außerdem würde ich das erste a auf "eleventh" schieben
