### ISSUE TITLE
Warpath

### ISSUE THREAD

**Issue by Tobias-Trautmann** [Tobias-Trautmann/Liederschuh_Issues#4]
Wir haben für den Refrain von Warpath keine Akkorde. Bitte stellt welche zur Verfügung oder erklärt, wie diese übertragen werden.
![image](https://user-images.githubusercontent.com/59808547/123183133-2d486e00-d491-11eb-8d08-8a8d61a91333.png)

**Comment by peribaeri** [comment]
m.W.n. sind das genau die gleichen Akkorde wie für die Strophe - die Weise des Refrains ist auch gleich wie die der Strophe

**Comment by Tobias-Trautmann** [comment]
per hats anders formatiert jetzt passts
